### ISSUE TITLE
elveh DTE only showing in km

### ISSUE THREAD

**Issue by benk016** [itchannel/fordpass-ha#144]
Just getting this setup, Everything is looking good, except on this field. It shows km instead of miles no matter what the plugin is set to show. All other fields show miles normally. 

ElVehDTE : 261.399994
Actual range according to my fordpass : 163

**Comment by itchannel** [comment]
I'll add this change in the next release as it currently doesn't change the value based upon the chosen unit for elVehDTE

**Comment by itchannel** [comment]
@benk016 Should be fixed in the latest version

**Comment by benk016** [comment]
OK, Its now working correctly in 1.30. Thank you!

**Comment by magnetic157** [comment]
Mine is still showing in Km despite being set to Miles in the preferences.
Odometer is showing in miles, but this is still in Km  `state: "{{state_attr('sensor.fordpass_elVeh', 'elVehDTE')}}" `

I'm on version 1.3
