### ISSUE TITLE
Window Position always shows as "Open"

### ISSUE THREAD

**Issue by MartyTremblay** [itchannel/fordpass-ha#56]
Attributes for all 4 windows show "Fully_closed_position" but entity state shows "Open"
```
DriverWindowPosition Fully_closed_position
PassWindowPosition Fully_closed_position
RearDriverWindowPos Fully_closed_position
RearPassWindowPos Fully_closed_position
```
Please refer to my JSON ouput found here https://github.com/itchannel/fordpass-ha/issues/52#issue-756622726

**Comment by itchannel** [comment]
Thanks looks like your car gives a different window position value that ones I've seen so far so will add in a check for it.

**Comment by MartyTremblay** [comment]
It's what I've noticed myself. Perhaps a simple Regex will do the trick.

**Comment by thisisbenwoo** [comment]
BTW, I haven't had a chance to report this, but I have the same issue with
my Explorer


---
*BenWoo* | +1 (212) 724-1188 | *this*is*ben*woo@gmail.com

**Comment by itchannel** [comment]
This should be fixed in #57

**Comment by itchannel** [comment]
Closing as this issue has been fixed

**Comment by paulgbrichardson** [comment]
I am still seeing this issue in 1.10

The State is Open but the attributes read as 

driverWindowPosition: Fully_Closed
passWindowPosition: Fully_Closed
rearDriverWindowPos: Fully_Closed
rearPassWindowPos: Fully_Closed

**Comment by MartyTremblay** [comment]
> I am still seeing this issue in 1.10
> 
> The State is Open but the attributes read as
> 
> driverWindowPosition: Fully_Closed
> passWindowPosition: Fully_Closed
> rearDriverWindowPos: Fully_Closed
> rearPassWindowPos: Fully_Closed

I'm seeing the same issue as well.

**Comment by Banzarykey** [comment]
Still getting this issue.

driverWindowPosition
Fully_Closed
passWindowPosition
Fully_Closed
rearDriverWindowPos
Fully_Closed
rearPassWindowPos
Fully_Closed

**Comment by MartyTremblay** [comment]
Fixed in #62  and released #63 

Thanks!
