### ISSUE TITLE
ValueError: could not convert string to float: ''

### ISSUE THREAD

**Issue by theOrakle** [itchannel/fordpass-ha#59]
Here is my stack:

```
version: 0.118.5
installation_type: Home Assistant Core
dev: false
hassio: false
docker: false
virtualenv: true
python_version: 3.8.5
os_name: Linux
os_version: 4.15.0-128-generic
arch: x86_64
timezone: America/Chicago
```

I am seeing the following error on versions 1.0.9 and 1.10, if I revert to 1.0.8 the issue goes away.

```
2020-12-13 07:14:24 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/opt/homeassistant/3.8.5/lib/python3.8/site-packages/homeassistant/helpers/update_coordinator.py", line 119, in _handle_refresh_interval
    await self.async_refresh()
  File "/opt/homeassistant/3.8.5/lib/python3.8/site-packages/homeassistant/helpers/update_coordinator.py", line 193, in async_refresh
    update_callback()
  File "/opt/homeassistant/3.8.5/lib/python3.8/site-packages/homeassistant/helpers/update_coordinator.py", line 245, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/opt/homeassistant/3.8.5/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 296, in async_write_ha_state
    self._async_write_ha_state()
  File "/opt/homeassistant/3.8.5/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 323, in _async_write_ha_state
    attr.update(self.device_state_attributes or {})
  File "/opt/homeassistant/config/custom_components/fordpass/sensor.py", line 214, in device_state_attributes
    return self.get_value("attribute")
  File "/opt/homeassistant/config/custom_components/fordpass/sensor.py", line 125, in get_value
    float(
ValueError: could not convert string to float: ''
```

I have not dug into the issue yet, but I'm happy to help debug.  

Thanks and love what you have done - much needed!

**Comment by itchannel** [comment]
So I believe this is the offending line 
```float(
                                self.coordinator.data["TPMS"]["leftFrontTirePressure"][
                                    "value"
                                ]
                            )```

Does your car not support TPMS?

Would you mind running the debug script and sending me the Json output from the vehicle array [Debug Script](https://github.com/itchannel/ford_debug)

**Comment by theOrakle** [comment]
My car does support TPMS.

Here is the JSON as requested:

`{'vin': 'ABC123', 'lockStatus': {'value': 'LOCKED', 'status': 'CURRENT', 'timestamp': '12-12-2020 18:12:34'}, 'alarm': {'value': 'ACTIVE', 'status': 'CURRENT', 'timestamp': '12-12-2020 18:12:34'}, 'PrmtAlarmEvent': {'value': 'Null', 'status': 'CURRENT', 'timestamp': '12-12-2020 18:12:34'}, 'odometer': {'value': 72861.0, 'status': 'CURRENT', 'timestamp': '12-12-2020 18:12:34'}, 'fuel': {'fuelLevel': 36.521856, 'distanceToEmpty': 272.5, 'status': 'CURRENT', 'timestamp': '12-12-2020 18:12:34'}, 'gps': {'latitude': '69', 'longitude': '-69', 'gpsState': 'UNSHIFTED', 'status': 'CURRENT', 'timestamp': '12-12-2020 18:12:34'}, 'remoteStart': {'remoteStartDuration': 0, 'remoteStartTime': 0, 'status': 'CURRENT', 'timestamp': '12-12-2020 18:12:34'}, 'remoteStartStatus': {'value': 0, 'status': 'CURRENT', 'timestamp': '12-12-2020 18:12:34'}, 'battery': {'batteryHealth': {'value': 'STATUS_GOOD', 'timestamp': '12-12-2020 18:12:32'}, 'batteryStatusActual': {'value': 12, 'status': 'CURRENT', 'timestamp': '12-12-2020 18:12:34'}}, 'oil': {'oilLife': 'STATUS_GOOD', 'oilLifeActual': 75, 'status': 'CURRENT', 'timestamp': '12-12-2020 18:12:34'}, 'tirePressure': {'value': 'STATUS_GOOD', 'timestamp': '04-07-2018 18:37:36'}, 'authorization': 'AUTHORIZED', 'TPMS': {'tirePressureByLocation': {'value': 0, 'status': 'CURRENT', 'timestamp': '12-12-2020 18:12:34'}, 'tirePressureSystemStatus': {'value': 'Systm_Activ_Composite_Stat', 'status': 'CURRENT', 'timestamp': '12-12-2020 18:12:34'}, 'dualRearWheel': {'value': None, 'status': 'LAST_KNOWN', 'timestamp': '08-12-2017 21:25:26'}, 'leftFrontTireStatus': {'value': '', 'status': 'LAST_KNOWN', 'timestamp': '08-12-2017 21:25:26'}, 'leftFrontTirePressure': {'value': '', 'status': 'LAST_KNOWN', 'timestamp': '08-12-2017 21:25:26'}, 'rightFrontTireStatus': {'value': '', 'status': 'LAST_KNOWN', 'timestamp': '08-12-2017 21:25:26'}, 'rightFrontTirePressure': {'value': '', 'status': 'LAST_KNOWN', 'timestamp': '08-12-2017 21:25:26'}, 'outerLeftRearTireStatus': {'value': '', 'status': 'LAST_KNOWN', 'timestamp': '08-12-2017 21:25:26'}, 'outerLeftRearTirePressure': {'value': '', 'status': 'LAST_KNOWN', 'timestamp': '08-12-2017 21:25:26'}, 'outerRightRearTireStatus': {'value': '', 'status': 'LAST_KNOWN', 'timestamp': '08-12-2017 21:25:26'}, 'outerRightRearTirePressure': {'value': '', 'status': 'LAST_KNOWN', 'timestamp': '08-12-2017 21:25:26'}, 'innerLeftRearTireStatus': {'value': '', 'status': 'LAST_KNOWN', 'timestamp': '08-12-2017 21:25:26'}, 'innerLeftRearTirePressure': {'value': '', 'status': 'LAST_KNOWN', 'timestamp': '08-12-2017 21:25:26'}, 'innerRightRearTireStatus': {'value': '', 'status': 'LAST_KNOWN', 'timestamp': '08-12-2017 21:25:26'}, 'innerRightRearTirePressure': {'value': '', 'status': 'LAST_KNOWN', 'timestamp': '08-12-2017 21:25:26'}, 'recommendedFrontTirePressure': {'value': None, 'status': 'LAST_KNOWN', 'timestamp': '08-12-2017 21:25:26'}, 'recommendedRearTirePressure': {'value': None, 'status': 'LAST_KNOWN', 'timestamp': '08-12-2017 21:25:26'}}, 'firmwareUpgInProgress': {'value': False, 'timestamp': '08-09-2020 23:27:24'}, 'deepSleepInProgress': {'value': False, 'timestamp': '07-16-2018 13:08:14'}, 'ccsSettings': {'timestamp': '04-21-2017 17:27:00', 'location': -1, 'vehicleConnectivity': -1, 'vehicleData': -1, 'drivingCharacteristics': -1, 'contacts': -1}, 'lastRefresh': '12-12-2020 18:12:32', 'lastModifiedDate': '12-12-2020 18:12:34', 'serverTime': '12-15-2020 17:57:35', 'batteryFillLevel': {'value': 50.0, 'status': 'CURRENT', 'timestamp': '12-12-2020 18:12:34'}, 'elVehDTE': None, 'hybridModeStatus': {'value': 'NullState', 'status': 'CURRENT', 'timestamp': '12-12-2020 18:12:34'}, 'chargingStatus': {'value': 'NotReadyNullState', 'status': 'CURRENT', 'timestamp': '12-12-2020 18:12:34'}, 'plugStatus': {'value': 0, 'status': 'CURRENT', 'timestamp': '12-12-2020 18:12:34'}, 'chargeStartTime': {'value': '01-01-2010 00:00:00', 'status': 'CURRENT', 'timestamp': '12-12-2020 18:12:34'}, 'chargeEndTime': {'value': '01-01-2010 00:00:00', 'status': 'CURRENT', 'timestamp': '12-12-2020 18:12:34'}, 'preCondStatusDsply': None, 'chargerPowertype': None, 'batteryPerfStatus': None, 'outandAbout': {'value': 'PwPckOffTqNotAvailable', 'status': 'CURRENT', 'timestamp': '12-12-2020 18:12:34'}, 'batteryChargeStatus': None, 'dcFastChargeData': None, 'windowPosition': {'driverWindowPosition': {'value': 'Fully_closed_position', 'status': 'CURRENT', 'timestamp': '12-12-2020 18:12:34'}, 'passWindowPosition': {'value': 'Fully_closed_position', 'status': 'CURRENT', 'timestamp': '12-12-2020 18:12:34'}, 'rearDriverWindowPos': {'value': 'Undefined_window_position', 'status': 'CURRENT', 'timestamp': '12-12-2020 18:12:34'}, 'rearPassWindowPos': {'value': 'Undefined_window_position', 'status': 'CURRENT', 'timestamp': '12-12-2020 18:12:34'}}, 'doorStatus': {'rightRearDoor': {'value': 'Closed', 'status': 'CURRENT', 'timestamp': '12-12-2020 18:12:34'}, 'leftRearDoor': {'value': 'Closed', 'status': 'CURRENT', 'timestamp': '12-12-2020 18:12:34'}, 'driverDoor': {'value': 'Closed', 'status': 'CURRENT', 'timestamp': '12-12-2020 18:12:34'}, 'passengerDoor': {'value': 'Closed', 'status': 'CURRENT', 'timestamp': '12-12-2020 18:12:34'}, 'hoodDoor': {'value': 'Closed', 'status': 'CURRENT', 'timestamp': '12-12-2020 18:12:34'}, 'tailgateDoor': {'value': 'Closed', 'status': 'CURRENT', 'timestamp': '12-12-2020 18:12:34'}, 'innerTailgateDoor': {'value': 'Closed', 'status': 'CURRENT', 'timestamp': '12-12-2020 18:12:34'}}, 'ignitionStatus': {'value': 'Off', 'status': 'CURRENT', 'timestamp': '12-12-2020 18:12:34'}, 'batteryTracLowChargeThreshold': None, 'battTracLoSocDDsply': None, 'dieselSystemStatus': None}`

**Comment by theOrakle** [comment]
I updated my VIN, Lat, & Long to protect the innocent...

As far as TPMS - it looks like the answer is "sort of", but the JSON explains why it always thinks my windows are open as well.

![FP_TPMS](https://user-images.githubusercontent.com/37029980/102254701-9a6dbc00-3ece-11eb-811c-f3d97dbebb59.png)

**Comment by itchannel** [comment]
Ok it looks like your car doesn't actually give the tyre pressures which is why it's erroring. I will have to add a check to ignore tyre pressures with the none object the rest will return 0. Although I do wonder if down the line your car might actually give tyre pressures as it responds with "0" for some rather than None. 

I can fix the windows issue, I've come across a number of different window statuses depending on the car model. Your car appears to respond with "Undefined_window_position" which I can now add as a check and discard that value.

**Comment by itchannel** [comment]
Should be fixed in the latest update #60

**Comment by theOrakle** [comment]
Error is gone.  Thank you.

Window still shows as open, but let's see what others get in their status as I'm sure when more people find the integration, you get a bigger picture and I may be an anomaly.

**Comment by theOrakle** [comment]
> Should be fixed in the latest update #60

Looks like this is back...
